backend:
  name: github
  branch: master # Branch to update (optional; defaults to master)
  open_authoring: true
  repo: brob/plug11ty.com # Path to your GitHub repository

publish_mode: editorial_workflow
media_folder: "assets/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "categories"
    label: "Categories"
    folder: "categories"
    create: true
    fields: 
      - { label: "Category Name", name: "title", widget: "string" }
      - { label: "Body", name: "body", required: false, widget: "markdown" }
  - name: "plugins"
    label: "Plugins"
    folder: "plugins"
    create: true
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "/plugin.njk" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Readme Raw URL", name: "readmeUrl", widget: "string", hint: "URL to raw readme file. the file should be Markdown, preferrably on GitHub. This takes the place of the body field here" }
      - label: "Categories"
        name: "categories" 
        widget: "relation"
        collection: "categories"
        searchFields: ["title"]
        valueField: "title"
        required: false
        multiple: true  
      - label: "Maintainer Info"
        name: "maintainer" 
        widget: "object" 
        required: false
        fields: 
          - label: "Maintainer Name"
            name: "name"
            widget: "string"
            required: false
          - label: "Maintainer URL"
            name: "url"
            widget: "string"
            required: false
      
      - { label: "GitHub/NPM URL", name: "githubUrl", widget: "string", required: false }
      - { label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", required: false, widget: "markdown", hint: "Only use this if you haven't provided a GitHub Readme URL"}